global:
  scrape_interval: 1m # By default, scrape targets every 15 seconds.

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090','192.168.18.3:9182']
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.18.11:9100']

  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - api_server: 'https://192.168.18.4:6443'
        role: endpoints
        bearer_token_file: '/var/run/secrets/kubernetes.io/serviceaccount/token'
        tls_config:
          ca_file: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
          insecure_skip_verify: true

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - api_server: 'https://192.168.18.4:6443'
        role: node
        bearer_token_file: '/var/run/secrets/kubernetes.io/serviceaccount/token'
        tls_config:
          ca_file: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
          insecure_skip_verify: true

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - api_server: 'https://192.168.18.4:6443'
        role: pod
        bearer_token_file: '/var/run/secrets/kubernetes.io/serviceaccount/token'
        tls_config:
          ca_file: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
          insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+):(?:\d+);(\d+)
        replacement: ${1}:${2}