apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: monitoring
  labels:
    app: test-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '80'
spec:
  serviceAccountName: prometheus
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      ports:
        - containerPort: 80
